# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nupzial-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: npm

      - name: npm install, build, and test
        run: |
          npm ci 
          npm run build

      - name: Upload dist artifact           
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: dist 


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download dist artifact          
        uses: actions/download-artifact@v4
        with:
          name: vite-dist
          path: ./dist
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nupzial-web'
          slot-name: 'Production'
          package: .

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3C59087A9BCD441BADD6EF508BAD71BF }}

